uikit/uikit

docs/documentation_javascript.html

update name checkdisplay event

---

src/js/core/modal.js

Change the markup of the undocumented but oh so usefull modal.dialog to comply with new modal layout.

change dialog footer

---

src/js/components/sticky.js

keeps sticky element in container, as requested in #905 
Puzzling with elements-heights and scrollheights around line 190 is really nasty, not sure if there is a more elegant way around it...

sticky in container

---

src/less/components/accordion.less

Thanks to Netbeans and Ilya :)

missing semicolon

---

docs/grid.html

Develop branch push -- should close https://github.com/uikit/uikit/pull/882

Missing /div

---

docs/slideshow.html

match example to source

---

docs/cover.html

Since it is included in the core.

remove inclusion js

---

docs/slider.html

Little typo in http://getuikit.com/docs/slider.html#center

typo in slider doc

---

src/js/components/lightbox.js

Set AMD definition as for plugin

Fix AMD definition for component lightbox

---

docs/dropdown.html

add hoverDelayIdle to dropwdown doc

---

src/js/core/toggle.js
tests/core/toggle.html

fixes https://github.com/uikit/uikit/issues/1339
I'm not sure if this is desired behaviour, please advice.

fix different states in totoggle elements

---

CHANGELOG.md
docs/slider.html
src/js/components/slider.js
tests/components/slider.html

As asked in https://github.com/uikit/uikit/issues/1367 (ao)

slider autoplay option

---

src/less/core/contrast.less

contrast: decouple vars from other components

---

src/less/core/panel.less

Prevent negative margin on nested boxes

Negative margin only on first child teaser

---

src/js/components/sticky.js

Added a status trigger that fires when the element is fixed at the top or released from top.

Added status trigger to sticky.js

---

src/js/core/tab.js

force navigation dropdown to drop only down.

Prevent flip on responsive tab

---

src/js/components/form-select.js

form-select with input as target

---

docs/modal.html

Prevent first modal to close when opening second by adding modal:false in data-uk-modal

http://getuikit.com/docs/modal.html update

---

docs/modal.html

Although most options are reviewed in the page, I think an overview would make sense, as most components have it.

add overview of javascript options

---

docs/text.html
src/less/core/text.less
tests/core/text.html

Add text transform utility classes for capitalize, lowercase and uppercase.
Update docs and tests.
Issue: 1706

Add text transform utility classes for capitalize, lowercase and uppercase

---

CHANGELOG.md

Needed for the transition to work instead of just letting it pop to the side. At least this is my experience.

Update offcanvas.less regarding offcanvas page transition

---

src/js/components/lightbox.js

to avoid errors on https sites

Remove protocol from api call

---

docs/offcanvas.html

Animation Modes anchor was set to flip-modifier.  It is now set to #animation-modes

Fixes Animation Modes Anchor

---

docs/smooth-scroll.html

Add info about the scrollToElement() function and JS options to the docs

---

docs/documentation_get-started.html

This error occurred in a paragraph.

Corrected spelling of the word "additional."

---

docs/lightbox.html

The lightbox demo for iframe isn't working because of mixed content.
https://getuikit.com/docs/lightbox.html

Fix mixed content error on iframe lightbox

---

src/js/api/component.js

Missing semicolons

---

docs/smooth-scroll.html

There is a closing bracket missing.

Missing close bracket

---

src/less/components/margin.less

Space before !important

---

tests/countdown.html
tests/cover.html
tests/form.html
tests/index.html
tests/lightbox.html
tests/modal.html
tests/navbar.html
tests/offcanvas.html
tests/position.html
tests/scroll.html
tests/upload.html
tests/utility.html

Please add new feature to make one page scroll or div to div scroll like **scrollify js**, these will be cool for presentation website, I have try to use uk-scrollspy-nav, but i can't trigger a specific to make smooth scroll.

Add one page scroll or div to div scroll !

---

src/js/components/upload.js

This PR allow setting a size_limit per file

Upload size limit

---

build/util.js

I noticed sources are compiled with a wrong year inside the banner.
I did not rebuild because I assumed the pull request would be denied in order to prevent potential malware from being merged.

Updated year in build banner copyright notice

---

dist/js/uikit.js

This was just causing an issue with some of our usage of the utils functions.

Fix variable ref

---

composer.json

build:Adds back missing composer.json file

---

tests/js/index.js

removed redundant call

---

src/js/core/overflow-auto.js

This allows to developer to configure the min-height of the overflowing content.

[Overflow Auto] Make min-height configurable
