uikit/uikit

docs/modal.html
src/less/core/modal.less
tests/core/modal.html

To prevent modals with small messages to be too high, it is not desirable to have a min-height applied to the default `uk-modal-dialog` class.
A dialog with one line and a default modal-header and footer is also too high:
Applying the `min-height` to the `uk-modal-dialog-lightbox` was suggested by @aheinze in the chat. It solves this problem, but it would mean breaking existing markup for modals with spinners.
I didn't edit changelog in this PR, but if this is merged, it should be mentioned in update guidelines.

move min-height for spinner to uk-modal-dialog-lightbox

---

themes/default/base.less

Delete @base-blockquote-small-color, which is no longer used.

Unused variable in base.less (default theme)

---

docs/text.html

Add .uk-text-left-small and .uk-text-left-medium classes (introduced in 2.16.0).

Add missing classes do text.html doc

---

docs/icon.html

Non-existing class .align-left, there should be .uk-align-left

Typo in docs - icon.html

---

gulpfile.js

themes which are added as symlinks do not get parsed by indexthemes task since fs.isDirectory() returns false; added OR fs.isSymbolicLink()

fix(gulp/indexthemes): add support for symlinks in themefolders

---

docs/flex.html

The example in the [flex docs](http://getuikit.com/docs/flex.html) is not aligned properly in Chrome:
It seems to me that this example used to be a centered one, and some markup was left over. The usage of both `uk-flex-center` and `uk-flex-space-between` obviously confused Chrome.
I removed  `uk-flex-center` from markup and example markup, and removed the margin which is not needed when using space-between.

Fix space-between example

---

docs/dropdown.html
src/js/core/dropdown.js

The dropdown component now throws a hide.uk.dropdown event.
This lead me to the case, that the event was fired after the remainIdle-timeout and not immediately, when it was hidden by hovering over another dropdown (line 135).
Because of this I also changed the active-handling a bit. The active-var now holds a reference to the (dropdown) object, not to the element (line 152). When hovering over another dropdown, the active element is no longer hidden by the new dropdown, but by calling the hide()-method of the active dropdown object (line 136). This way, the hide-method is the only place, that handles the hiding of a dropdown.
In the hide function I also clear the remainIdle timeout, to prevent the method to be called twice in the case described above.

added hide.uk.dropdown event

---

docs/progress.html

Classname of `uk-progress-striped` was not complete

correct classname progress docs

---

src/less/components/sticky.less

Noticed this when a sticky header was used on devices with lower frame-rates/video cards. Original thought was to use `transform3d(0, 0, 0)`, but that impacted elements along the z axis. This is a lower fidelity change that enabled hardware acceleration.

frame rate issues with sticky elements

---

src/js/components/slideshow.js

In the slideshow component:
If the show function is called with an index equal to the current one, the image at the slide becomes hidden. This fix returns from show with no action when this is the case.

Clean up transition when show is passed the current index

---

docs/cover.html

To match the actual example, `uk-flex` needs to be added to the `position-cover` element to actually work.

match example to actual code cover-docs

---

src/js/core/offcanvas.js

reported in #1087
Stack example on ember app:
Error while processing route: channel Syntax error, unrecognized expression: #/channels/dormroomtycoon Error: Syntax error, unrecognized expression: #/channels/dormroomtycoon
at Function.Sizzle.error (http://localhost:4200/assets/vendor.js:1611:8)
at Sizzle.tokenize (http://localhost:4200/assets/vendor.js:2228:11)
at Sizzle.select (http://localhost:4200/assets/vendor.js:2632:20)
at Function.Sizzle (http://localhost:4200/assets/vendor.js:1008:9)
at jQuery.fn.extend.find (http://localhost:4200/assets/vendor.js:2848:11)
at jQuery.fn.init (http://localhost:4200/assets/vendor.js:2965:38)
at Object.jQuery [as $] (http://localhost:4200/assets/vendor.js:193:10)
at HTMLDocument.<anonymous> (http://localhost:4200/assets/vendor.js:82201:37)
at …

Prevent offcanvas error when target is a link

---

src/js/components/sortable.js

leftover from prefixing. Don't think this does anything usefull :). https://github.com/uikit/uikit/commit/5c75488399d955e34b79c79c94b5688c887ad385#diff-06d21a7c7966b5e43a098e91c6879abbR118

cleanup sortable.js

---

docs/sortable.html

At http://getuikit.com/docs/sortable.html#javascript-options the description for the option `handleClass` sais `CSS selector to define elements which can trigger sorting`. But when adding a selector `.my-class`, an error `Uncaught Error: Syntax error, unrecognized expression: ..my-class` is thrown.
Changing the text to `Custom class to..` fixes the confusion.

Update datatype sortable option

---

src/less/components/sticky.less

Since you can enable the sticky component without the `data-uk-sticky` attr (like in [Helios](http://yootheme.com/demo/themes/wordpress/2015/helios/?style=default), this makes the selector fix more general -- based on the `data-uk-sticky-placeholder` direct child.

Made selector more general

---

docs/animation.html

The animations are triggered by hovering, not by clicking. http://getuikit.com/docs/animation.html

Rename trigger of animations in animation docs

---

src/less/core/overlay.less

The markup example of the overlay component is out of date.

update markup example overlay

---

src/js/components/form-password.js
tests/components/form-password.html

Allows html in the custom label. There might be a usability issue with the markup though. The data attribute has to be in single quotes, and the value in double quotes, slashing the doubles in the html.
`data-uk-form-password='{lblShow: "<i class=\"uk-icon-eye\"></i>", lblHide: "<i class=\"uk-icon-eye-slash\"></i>"}'`

Allow html in label form-password

---

docs/block.html

You accidentally a word in the docs for the block component

Forgot the word "remove" in the padding section

---

src/js/components/tooltip.js

Fix error when tooltips with empty (but present) title, introduced in 4db3a9c.
Also unnecessary argument `title` is not a local variable.

Tooltip fix

---

src/less/core/description-list.less
tests/core/description-list.html

The combination of `uk-description-list-horizontal` and `uk-description-list-line` results in a list with only lines between the `dt` elements:
The list gets crooked because the `dd`s lack margin and stack up to the top.
This PR solves that by adding the margin and border to the `dd` as well when both  `uk-description-list-horizontal` and `uk-description-list-line` are used on the `dl`.

description list horizontal with line

---

src/js/components/datepicker.js
tests/components/datepicker.html

-When listening to the `change` event on a datepicker, you'd have to retrieve the current value from the DOM, even when you have the datepicker instance at hand. This PM sets the value of `this.current` to the selected date.
-I also used the default `hide()` function from the datepicker, so that the `hide.uk.datepicker` event is triggered.
-The existing logic for mindate/maxdate in the `getRows()` function did not work, instead that logic was done in the template function. I moved the working part to the `getRows()` function, since that seems to make more sense.
-I don't think `(ele.hasClass("uk-datepicker-next") ? 1:-1)` could ever be a non-integer value, why multiply it by 1?

Datepicker 'current' value on change event and some cleanup

---

src/js/core/button.js

Now you can easy change Checkbox buttons and Radio buttons active class for better experience.
for example use ```data-uk-button-radio="{ activeClass: 'uk-button-primary'}"```

added activeClass option to button group component

---

src/js/components/lightbox.js

The size of the lightbox a Youtube video is shown in, is determined by the size of the default preview image youtube serves under the url `'//img.youtube.com/vi/'+id+'/0.jpg'`, usually 480x360 pixels (See [SO](http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api/20542029#20542029)). This causes the lightbox never to be bigger than that.
Many users request bigger Youtube lightboxes, and it can be done.
On high resolution videos the `'//img.youtube.com/vi/'+id+'/maxresdefault.jpg'` image provides a full res image if available, making it possible to create bigger lightboxes. A fallback has to be provided, because not all videos have that image.
Which gives a new problem, as the fallback as it was in place does not actually work. Although …

youtube lightbox sizing

---

.npmignore
package.json

This should make life easier for people using browserify, webpack or (in my case) JSPM/SystemJS.  This still doesn't solve the need for `window.jQuery`, but by publishing `dist` and including a `main:`, people like me can `require('uikit')` and everything should just work.
This branch includes an [earlier PR](https://github.com/uikit/uikit/pull/1434) (raised by @elliottsj).  It also adds the `main` attribute to `package.json`.
I'm raising as a new PR as the `CONTRIBUTING.md` says to open a PR into `develop`, rather than `master`.

Make UIkit integrate a little more cleanly with NPM

---

src/js/core/touch.js

The Zeptos touch.js file assumes the variable touch.el will be a Zepto object containing a trigger method in several event listeners. It makes the assumption that the touchstart event will always be called before touchend event, which is inaccurate for lots of reasons.
See: madrobby/zepto#943

Touchjs - TypeError: 'undefined' is not an object (evaluating 'touch.el.trigger')

---

src/js/components/slider.js
tests/components/slider.html

Using the slider with infinite:false and elements with custom widths inside, did not show the last element fully, when it did not fit into the viewport. Here is an example of the bug:
http://codepen.io/anon/pen/vNGooG?editors=100
As you can see, element Nr. 6 is not fully shown, because the slider does not want to move element nr 4 in focus, because nr 3 would than be cut off. But I would say: better cut one off, you have already seen, than not showing the last one. What do you think?
So in this fix, the last element will be fully shown (in this case nr. 6), the focus will be moved to the next element (in this case nr. 4) and the element on the left will be cut off (in this case nr. 3).
Includes a test for this case as well.

fix for slider not showing the last element

---

docs/datepicker.html

I was trying to use the datepicker and it took my a while to understand why the element was not displayed properly.

Add missing type in the datepicker markup example

---

docs/slider.html

`threshold` was defined as boolean, but is integer
I also updated the corresponding default value of 10px
`autoplay` has mixed up table cells (default ↔ possible values)

#Fix slider javascript parameter docs

---

docs/dropdown.html
src/js/core/dropdown.js

If use for dropdown option `mode:'click'` - dropdown is hiding after
user's click. But if this option 'hover' - it not hides. This commit is
fixing this problem.

[=] Fix hiding dropdown on click with option `mode:'hover'` for dropdown or items with class `uk-dropdown-close`

---

CHANGELOG.md
src/js/components/parallax.js

Bug fix left and right bars when the image width is smaller then the element width.

Fixed parallax for images with smaller width

---

src/js/core/core.js

This PR reduces the memory leak by not changing the reference of the closure `memory` and removes the closure `dir`. It creates a new object to fire the event, so it is impossible for a function consuming the event to hold onto the closure, which was also causing a memory leak.
In the wild, this allows smooth animations while scrolling and dramatically increases animation performance.

Fixes #1751: Fix memory leak and lots of redrawing in Chrome

---

docs/nestable.html
src/js/components/nestable.js

Useful for manually declaring items that shouldn't be nested, such as bottom-level items. It works well for me, and doesn't conflict with other nesting restrictions in my testing.

Added noChildrenClass to Nestable component

---

src/js/components/datepicker.js

When the data-date value does not resolve to a valid Date(), the value
set in the element is cleared.
It could be better to do this _only_ if [data-date=""], happy to change
to support that.

Support for having a 'clear' function.

---

src/js/components/grid.js

Here's a fix for Uncaught TypeError: _getSize is not a function.
Which is appear when using Dynamic grid.
Also this issue is described here: [https://github.com/uikit/uikit/issues/1905](url)

Fix for Dynamic Grid _getSize is not a function

---

src/js/core/core.js

Always cancel any outstanding requestAnimationFrames before enqueuing another...
In iOS Safari, there can end up being hundreds and hundreds of requestAnimationFrames enqueued. This isn't ideal, as it can take 500ms+ to process them all in one frame.

Fix where many requestanimationframes can exist

---

src/js/components/slideshow.js

Kind of an edge-case, but if you create a slideshow within a slideshow (whoever want's to do this ;)) the parent-slideshow also uses the slides of the child-slideshow. That means the parent slideshow tries to navigate through the slides of the child slideshow as well, resulting in an unexpected behavior.
Adding `:first` to the container-selector fixes this.

fix(slideshow): only use first element as container

---

src/js/core/scrollspy.js

It doesn't seem like the topoffset option has the effect it should, it factors into the calculation in isInView but then is left out when looking for the target.

Include topoffset in scrollspy target calculation

---

docs/lightbox.html
src/js/components/lightbox.js

If the option is set to true, the `allowfullscreen` attribute will be added to Iframes in the Lightbox, allowing videos to toggle fullscreen.
This is required for Youtube and Vimeo. Seems like Vimeo recently changed their players behavior because toggling fullscreen was working without this attribute a few month ago. On the current UIkit (Version 2.26.3) docs you can observe, that toggling fullscreen does not work for Vimeo or Youtube.
Tested
- IE 11 (W10)
- Edge (W10)
- Firefox (W10)
- Chrome (W10)

lightbox: add option for allowfullscreen

---

docs/upload.html
src/js/components/upload.js

I use file uploader component to directly upload files from web-browser to Rackspace Cloud. To achieve that I needed to use HTTP method "PUT" instead of default "POST". This already can be done, so I added this feature to documentation.
I also added a feature to specify additional headers, for example  'Access-Control-Allow-Origin', or auth token.
This addition will make using of file upload component more flexible.

Documenting 'method' setting, adding 'headers' setting

---

src/js/components/datepicker.js

In my timezone, and in the afternoon, maxDate with a fixed date (rather
than an integer value) was disallowing the specified value.
This was because of some DST-related fixes I submitted: this changes
should fix that.

Handle maxDate correctly.

---

src/js/core/dropdown.js

Add functionality to automatically apply a uk-dropdown-autoflip class to the dropdown element, when the boundary check results in a flipping of the dropdown (e.g. not enough space on the right, so flip it to the left and add uk-dropdown-autoflip).

feat(dropdown): add uk-dropdown-autoflip modifier

---

src/js/components/datepicker.js
tests/components/datepicker.html

As stated in the issue #2024, when the `minDate` option is set with a string, the default date for the datepicker is the min date. This PR remove this functionality, making it behave in the same way that when the `minDate` option is set with an integer.

Uses today as the default date even when the 'minDate' option is set (issue #2024)

---

src/less/components/tooltip.less
tests/components/tooltip.html

Break words inside of tooltips when they overflow it's space (Fixes issue #2051)

Break words inside of tooltips (issue #2051)

---

src/less/core/dropdown.less

Remove dotted line shown by default in Firefox on focused dropdowns (issue #2038).

Remove dotted line shown by default in Firefox on focused dropdowns (issue #2038)

---

src/js/core/tab.js

I created a list like this one bellow
`<ul class="uk-tab" data-uk-tab>`
`<li><a>...</a></li>`
`<li><a>...</a></li>`
`</ul>`
But when I click on List on Responsive dropdown, It doesn't switch, I
found out that dosn't happen because <a> in responsive list don't have
data-index attribue.

Fix: Switching dosn't work when using <a> without href attribute on responsive list

---

src/js/core/switcher.js

I'm trying to do following:
```javascript
$(function() {
UIkit.tab("#tabs")[0].show(2);
});
```
This doesn't work when the page is opened in background via middle mouse button, because FastDOM requestAnimationFrame callback is not called and Tab/switchers's `update` method is not called until after user switches to the tab, and `show` depends on data initialized in `update`.
Maybe I'm doing it wrong? Is there a way to wait until the first frame is painted and all components are initialized?

Fix switcher.show() when used in onReady event

---

src/less/components/width.less

On certain viewport sizes e.g 1280px wide IE10/IE11/Edge13/Edge14 Would round the numbers too high, causing 3 and 6 column grids, fold onto new lines.
By adding the extra decimal places in it prevents the rounding pushing items onto new lines.
Effectively turns this
into

Fixes Edge/IE11 Rounding issues

---

src/js/core/height-match.js

The uk-height-match attribute does not work on the initial page load, only when the browser window is resized.

Fix height-match not working on initial page load

---

src/less/theme/_import.less

in components _import.less we have:
`// Utilities`
in theme _import.less we have:
`// Utility`
this PR remove the difference

Use the same name as in components _import.less

---

src/js/util/dom.js

Right now if you pass an origin modifier to `UIkit.util.animate()` it gets prefixed with `uk-animation-`, which is [according to the docs](https://getuikit.com/docs/animation#origin-modifiers) wrong.
**Example:**
```js
// Programmatically animate something
UIkit.util.animate(element, 'uk-animation-scale-up', 400, 'bottom-right', false);
```
```html
<div class="uk-animation-scale-up uk-animation-enter uk-animation-bottom-right"></div>
<div class="uk-animation-scale-up uk-animation-enter uk-transform-origin-bottom-right"></div>
```

Fix origin modifier for programmatically triggered animations

---

src/js/util/selector.js

On my android phone browser "Browser" Off-canvas and Modal does not work without this

function matches (js/util/selector) support some android native browsers

---

src/js/components/upload.js

```log
Invalid File Size: *.jpeg Bytes Max
```
```log
Invalid File Size: 1000 Kilobytes Max
```
On [line 115](https://github.com/uikit/uikit/blob/develop/src/js/components/upload.js#L115) `maxSize` gets multiplied by a factor of 1000 and [1000 Bytes = 1 Kilobyte](https://www.google.ch/search?q=1+kilobyte).

Fix error message for maxSize option

---

src/js/core/icon.js
src/js/core/svg.js

* https://github.com/PolymerElements/iron-iconset-svg/issues/46
* https://allyjs.io/tutorials/focusing-in-svg.html

fix(icon): make SVG icons non-focusable in IE

---

src/js/core/svg.js

This fixes #4132 .
The error was caused due to `svg` element not being rendered. Added a condition to check if the element is visible.

fix svg parallax fail when element is not visible

---

src/js/core/modal.js
tests/modal.html

Currently the value of `UIKit.modal.prompt` does not properly escape double quotation marks ("), resulting in any text behind the quotes overflowing into the modal's HTML.
For example: 
```
UIkit.modal.prompt("Name:", 'start "quote" end').then(function (name) {
console.log("Prompted:", name);
});
```
```
<div class="uk-modal-body">
<label>Name:</label>
<input class="uk-input" value="start " quote"="" end"="" autofocus="">
</div>
```
https://codepen.io/inventivetalent/pen/PogvrLX
This PR moves the [inline input value assignment](https://github.com/uikit/uikit/blob/main/src/js/core/modal.js#L129) to use the `input.value` setter instead.

fix: Quotation issue in modal prompt
